In [10]:
from functions import *
from keras.models import load_model
import pandas as pd
import numpy as np
import cv2
import pprint as pp

In [11]:
emotion_model_path = 'models/fer2013_mini_XCEPTION.119-0.65.hdf5'
cascade_model_path = 'models/haarcascade_frontalface_default.xml'

emotion_classifier = load_model(emotion_model_path)
face_classifier = cv2.CascadeClassifier(cascade_model_path)

emotion_target_size = emotion_classifier.input_shape[1:3]

emotion_labels = {
    0: 'angry',
    1: 'disgust',
    2: 'fear',
    3: 'happy',
    4: 'sad',
    5: 'surprise',
    6: 'neutral'
}

C:\Users\Josh\Anaconda3\envs\PythonData\lib\site-packages\keras\engine\saving.py:327: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '


In [12]:
emotion_offsets = (20, 40)

emotion_window = []

picture = cv2.imread('img/graytest.jpg', 0)

In [14]:

# gray_image = cv2.imread_gray_scale(picture, cv2.COLOR_BGR2GRAY)
gray_image = picture
    
    
# faces = face_classifier.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30), flags=cv2.CASCADE_SCALE_IMAGE)
faces = face_classifier.detectMultiScale(gray_image, 1.4, 5, minSize=(30,30))    
for face_coords in faces:

    x1, x2, y1, y2 = apply_offsets(face_coords, emotion_offsets)
    gray_face = gray_image[y1:y2, x1:x2]
    gray_face = cv2.resize(gray_face, (emotion_target_size))
    print(gray_face)

gray_face = preprocess_input(gray_face, True)
gray_face = np.expand_dims(gray_face, 0)
gray_face = np.expand_dims(gray_face, -1)
emotion_prediction = emotion_classifier.predict(gray_face)
emotion_probability = np.max(emotion_prediction)
emotion_label_arg = np.argmax(emotion_prediction)
emotion_text = emotion_labels[emotion_label_arg]
emotion_window.append(emotion_text)

    

[[221 222 224 ... 233 231 231]
 [221 221 223 ... 236 235 232]
 [219 220 222 ... 239 238 236]
 ...
 [140 142 145 ... 164 145 155]
 [123 125 130 ... 164 140 153]
 [120 124 126 ... 154 143 143]]


In [18]:
print(emotion_prediction)
print(np.max(emotion_prediction))
print(np.argmax(emotion_prediction))

[[1.5441360e-04 9.8404396e-09 4.2526319e-04 9.6796429e-01 8.7923094e-05
  3.8265658e-03 2.7541488e-02]]
0.9679643
3


In [7]:
picture.shape

(480, 600)

In [15]:
faces

array([[ 98,  90, 253, 253]], dtype=int32)